// db/ensureTenantSettings.js — يضمن كل أعمدة tenant_settings (تُشغَّل عند كل إقلاع — آمنة)
// ملاحظة: لا نلمس سياسات RLS هنا — ensureTenantIsolation هو المسؤول عنها
// (إعادة إنشاء السياسة هنا كانت تمسح app.bypass_rls وتكسر الإعدادات).

const { pool } = require('./pool');

let ensured = false;

const ENSURE_TENANT_SETTINGS_SQL = `
ALTER TABLE tenant_settings
  ADD COLUMN IF NOT EXISTS patients_prefix VARCHAR(10) NOT NULL DEFAULT 'C',
  ADD COLUMN IF NOT EXISTS patients_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS patients_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS suppliers_prefix VARCHAR(10) NOT NULL DEFAULT 'S',
  ADD COLUMN IF NOT EXISTS suppliers_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS suppliers_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS doctors_prefix VARCHAR(10) NOT NULL DEFAULT 'D',
  ADD COLUMN IF NOT EXISTS doctors_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS doctors_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS employees_prefix VARCHAR(10) NOT NULL DEFAULT 'E',
  ADD COLUMN IF NOT EXISTS employees_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS employees_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS receipts_prefix VARCHAR(10) NOT NULL DEFAULT 'RC',
  ADD COLUMN IF NOT EXISTS receipts_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS receipts_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS payments_prefix VARCHAR(10) NOT NULL DEFAULT 'PY',
  ADD COLUMN IF NOT EXISTS payments_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS payments_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS journal_docs_prefix VARCHAR(10) NOT NULL DEFAULT 'JV',
  ADD COLUMN IF NOT EXISTS journal_docs_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS journal_docs_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS bank_entries_prefix VARCHAR(10) NOT NULL DEFAULT 'BE',
  ADD COLUMN IF NOT EXISTS bank_entries_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS bank_entries_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS purchase_invoices_prefix VARCHAR(10) NOT NULL DEFAULT 'PI',
  ADD COLUMN IF NOT EXISTS purchase_invoices_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS purchase_invoices_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS credit_notes_prefix VARCHAR(10) NOT NULL DEFAULT 'CN',
  ADD COLUMN IF NOT EXISTS credit_notes_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS credit_notes_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS debit_notes_prefix VARCHAR(10) NOT NULL DEFAULT 'DN',
  ADD COLUMN IF NOT EXISTS debit_notes_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS debit_notes_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS ai_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS ai_api_key TEXT,
  ADD COLUMN IF NOT EXISTS ai_base_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS ai_vision_model VARCHAR(120),
  ADD COLUMN IF NOT EXISTS ai_provider VARCHAR(40) NOT NULL DEFAULT 'openai',
  ADD COLUMN IF NOT EXISTS wa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS wa_provider VARCHAR(40) NOT NULL DEFAULT 'compatible',
  ADD COLUMN IF NOT EXISTS wa_api_token TEXT,
  ADD COLUMN IF NOT EXISTS wa_phone_number_id VARCHAR(120),
  ADD COLUMN IF NOT EXISTS wa_base_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS wa_default_country VARCHAR(8) NOT NULL DEFAULT '972',
  ADD COLUMN IF NOT EXISTS wa_template_appointment VARCHAR(120),
  ADD COLUMN IF NOT EXISTS wa_template_reminder VARCHAR(120),
  ADD COLUMN IF NOT EXISTS wa_template_payment VARCHAR(120),
  ADD COLUMN IF NOT EXISTS wa_template_balance VARCHAR(120),
  ADD COLUMN IF NOT EXISTS wa_auto_appointment BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS wa_auto_reminder BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS wa_auto_payment BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS currency_rates_confirmed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS role_permission_defaults JSONB,
  ADD COLUMN IF NOT EXISTS number_digits VARCHAR(16) NOT NULL DEFAULT 'western',
  ADD COLUMN IF NOT EXISTS time_format VARCHAR(8) NOT NULL DEFAULT '12h',
  ADD COLUMN IF NOT EXISTS letterhead_layout JSONB NOT NULL DEFAULT '{}'::jsonb;
`;

async function ensureTenantSettingsSchema() {
  if (ensured) return;
  await pool.query(ENSURE_TENANT_SETTINGS_SQL);
  ensured = true;
}

module.exports = { ensureTenantSettingsSchema };
