-- ترقيم المستندات المحاسبية (سند قبض، صرف، …)

ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS entry_number VARCHAR(32);

CREATE UNIQUE INDEX IF NOT EXISTS idx_journal_entries_entry_number
  ON journal_entries(tenant_id, entry_number)
  WHERE entry_number IS NOT NULL;

ALTER TABLE tenant_settings
  ADD COLUMN IF NOT EXISTS receipts_prefix VARCHAR(10) NOT NULL DEFAULT 'RC',
  ADD COLUMN IF NOT EXISTS receipts_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS receipts_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS payments_prefix VARCHAR(10) NOT NULL DEFAULT 'PY',
  ADD COLUMN IF NOT EXISTS payments_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS payments_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS journal_docs_prefix VARCHAR(10) NOT NULL DEFAULT 'JV',
  ADD COLUMN IF NOT EXISTS journal_docs_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS journal_docs_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS bank_entries_prefix VARCHAR(10) NOT NULL DEFAULT 'BE',
  ADD COLUMN IF NOT EXISTS bank_entries_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS bank_entries_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS purchase_invoices_prefix VARCHAR(10) NOT NULL DEFAULT 'PI',
  ADD COLUMN IF NOT EXISTS purchase_invoices_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS purchase_invoices_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS credit_notes_prefix VARCHAR(10) NOT NULL DEFAULT 'CN',
  ADD COLUMN IF NOT EXISTS credit_notes_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS credit_notes_next INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS debit_notes_prefix VARCHAR(10) NOT NULL DEFAULT 'DN',
  ADD COLUMN IF NOT EXISTS debit_notes_width SMALLINT NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS debit_notes_next INT NOT NULL DEFAULT 1;
